---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - golang
      - bloodhound
      - gobuster
      - seclists
      - feroxbuster
      - xclip
      - docker.io
    state: latest
  become: true
  become_method: sudo

- name: Enable Docker service to start on boot
  systemd: 
    name: docker
    enabled: yes
    state: started