---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy: 
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop: 
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", location: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", location: "/opt/chisel" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", location: "/opt/peas" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", location: "/opt/peas" }
    - { repo: "itm4n/PrintSpoofer", regex: "PrintSpoofer64.exe", location: "/opt/potatoes"}
    - { repo: "BeichenDream/GodPotato", regex: "GodPotato-NET4.exe", location: "/opt/potatoes"}
    - { repo: "ohpe/juicy-potato", regex: "JuicyPotato.exe", location: "/opt/potatoes"}
    - { repo: "DominicBreuker/pspy", regex: "pspy64", location: "/opt/privesc" }
  async: 45
  poll: 0 
  become: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file: 
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined
